# Generated by Django 3.1.2 on 2020-12-21 23:12

from django.db import migrations, models
import django.utils.timezone
import portfolio.models
import uuid


class Migration(migrations.Migration):

    replaces = [('portfolio', '0001_squashed_0012_auto_20201023_2349'), ('portfolio', '0002_auto_20201031_2330'), ('portfolio', '0003_auto_20201031_2332'), ('portfolio', '0004_auto_20201031_2345'), ('portfolio', '0005_auto_20201101_2205'), ('portfolio', '0006_auto_20201103_2323'), ('portfolio', '0007_auto_20201120_1821'), ('portfolio', '0008_auto_20201129_1830'), ('portfolio', '0009_auto_20201129_2144'), ('portfolio', '0010_auto_20201203_1508'), ('portfolio', '0011_auto_20201222_0003')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Title of the project', max_length=50, null=True, verbose_name='Title')),
                ('intro', models.CharField(default=portfolio.models.project_default_intro, max_length=100, verbose_name='Introduction')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date:')),
                ('body', models.TextField(null=True, verbose_name='Text')),
                ('last_updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(editable=False, max_length=100, null=True)),
                ('category', models.CharField(choices=[('ALT', 'Other'), ('RES', 'Residential'), ('TER', 'Offices'), ('SAN', 'Hospitals'), ('PRO', 'Production'), ('SCO', 'Schools')], default='ALT', max_length=4, verbose_name='Functional category')),
                ('cost', models.CharField(choices=[('ALT', 'Other'), ('1K', '1K'), ('10K', '10K'), ('100K', '100K'), ('1M', '1M'), ('10M', '10M')], default='ALT', max_length=4, verbose_name='Cost of intervention')),
                ('site', models.CharField(blank=True, help_text='Something like "Rome - Monteverde"', max_length=100, null=True, verbose_name='Site')),
                ('status', models.CharField(choices=[('ALT', 'Other'), ('PRO', 'Designed'), ('COR', 'Under construction'), ('REA', 'Done')], default='ALT', max_length=4, verbose_name='Status of intervention')),
                ('type', models.CharField(choices=[('ALT', 'Other'), ('ARR', 'Furniture'), ('RIS', 'Refurbishment'), ('RES', 'Restoration'), ('AMP', 'Extension'), ('COS', 'Construction'), ('DEM', 'Demolition')], default='ALT', max_length=4, verbose_name='Type of intervention')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('-date',),
            },
        ),
    ]
