# Generated by Django 3.1.2 on 2020-10-25 21:20

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    replaces = [('portfolio', '0001_initial'), ('portfolio', '0002_auto_20201015_2304'), ('portfolio', '0003_auto_20201016_1209'), ('portfolio', '0004_auto_20201017_1757'), ('portfolio', '0005_project_body'), ('portfolio', '0006_auto_20201018_1616'), ('portfolio', '0007_auto_20201018_1956'), ('portfolio', '0008_auto_20201020_1700'), ('portfolio', '0009_delete_projectimage'), ('portfolio', '0010_auto_20201020_2326'), ('portfolio', '0011_auto_20201021_2014'), ('portfolio', '0012_auto_20201023_2349')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Il titolo del progetto', max_length=50, null=True, verbose_name='Titolo')),
                ('intro', models.CharField(default='Un altro progetto di architettura.APP!', max_length=100, verbose_name='Introduzione')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data:')),
                ('body', models.TextField(null=True, verbose_name='Testo')),
                ('last_updated', models.DateTimeField(editable=False, null=True)),
                ('slug', models.SlugField(editable=False, max_length=100, null=True)),
                ('category', models.CharField(choices=[('ALT', 'Altro'), ('RES', 'Residenziale'), ('TER', 'Terziario'), ('SAN', 'Sanitario'), ('PRO', 'Produttivo'), ('SCO', 'Scolastico')], default='ALT', max_length=4, verbose_name='Categoria funzionale')),
                ('cost', models.CharField(choices=[('ALT', 'Altro'), ('1K', '1K'), ('10K', '10K'), ('100K', '100K'), ('1M', '1M'), ('10M', '10M')], default='ALT', max_length=4, verbose_name="Costo dell'intervento")),
                ('site', models.CharField(blank=True, help_text='Va bene tipo "Roma - Monteverde"', max_length=100, null=True, verbose_name='Luogo')),
                ('status', models.CharField(choices=[('ALT', 'Altro'), ('PRO', 'Progettato'), ('COR', 'In corso'), ('REA', 'Realizzato')], default='ALT', max_length=4, verbose_name="Stato dell'intervento")),
                ('type', models.CharField(choices=[('ALT', 'Altro'), ('ARR', 'Arredamento'), ('RIS', 'Ristrutturazione'), ('RES', 'Restauro'), ('AMP', 'Ampliamento'), ('COS', 'Costruzione'), ('DEM', 'Demolizione')], default='ALT', max_length=4, verbose_name='Tipo di intervento')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
                'ordering': ('-date',),
            },
        ),
    ]
