# Generated by Django 4.0.3 on 2022-04-11 17:59

import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
from django.db import migrations, models

import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full", models.CharField(max_length=32, verbose_name="Name")),
                ("abbrev", models.CharField(max_length=4, verbose_name="Code name")),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ("abbrev",),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=100, null=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the project",
                        max_length=50,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_it",
                    models.CharField(
                        blank=True,
                        help_text="Title of the project",
                        max_length=50,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="Title of the project",
                        max_length=50,
                        null=True,
                        verbose_name="Title",
                    ),
                ),
                (
                    "intro",
                    models.CharField(
                        default=portfolio.models.project_default_intro,
                        max_length=100,
                        verbose_name="Introduction",
                    ),
                ),
                (
                    "intro_it",
                    models.CharField(
                        default=portfolio.models.project_default_intro,
                        max_length=100,
                        null=True,
                        verbose_name="Introduction",
                    ),
                ),
                (
                    "intro_en",
                    models.CharField(
                        default=portfolio.models.project_default_intro,
                        max_length=100,
                        null=True,
                        verbose_name="Introduction",
                    ),
                ),
                ("body", models.TextField(null=True, verbose_name="Text")),
                ("body_it", models.TextField(null=True, verbose_name="Text")),
                ("body_en", models.TextField(null=True, verbose_name="Text")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date:"
                    ),
                ),
                ("last_updated", models.DateTimeField(editable=False, null=True)),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        help_text='Something like "Rome - Monteverde"',
                        max_length=100,
                        null=True,
                        verbose_name="Site",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ALT", "Other"),
                            ("RES", "Residential"),
                            ("TER", "Offices"),
                            ("SAN", "Hospitals"),
                            ("PRO", "Production"),
                            ("SCO", "Schools"),
                        ],
                        default="ALT",
                        max_length=4,
                        verbose_name="Functional category",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ALT", "Other"),
                            ("ARR", "Furniture"),
                            ("RIS", "Refurbishment"),
                            ("RES", "Restoration"),
                            ("AMP", "Extension"),
                            ("COS", "Construction"),
                            ("DEM", "Demolition"),
                        ],
                        default="ALT",
                        max_length=4,
                        verbose_name="Type of intervention",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ALT", "Other"),
                            ("PRO", "Designed"),
                            ("COR", "Under construction"),
                            ("REA", "Done"),
                        ],
                        default="ALT",
                        max_length=4,
                        verbose_name="Status of intervention",
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        choices=[
                            ("ALT", "Other"),
                            ("1K", "1K"),
                            ("10K", "10K"),
                            ("100K", "100K"),
                            ("1M", "1M"),
                            ("10M", "10M"),
                        ],
                        default="ALT",
                        max_length=4,
                        verbose_name="Cost of intervention",
                    ),
                ),
                (
                    "activity",
                    models.ManyToManyField(
                        blank=True,
                        to="portfolio.activity",
                        verbose_name="Performed activities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="ProjectCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fb_image",
                    filebrowser.fields.FileBrowseField(
                        max_length=200, verbose_name="Image"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Will be used in captions",
                        max_length=100,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_it",
                    models.CharField(
                        blank=True,
                        help_text="Will be used in captions",
                        max_length=100,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        help_text="Will be used in captions",
                        max_length=100,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        null=True, verbose_name="Position"
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_carousel",
                        to="portfolio.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project carousel",
                "verbose_name_plural": "Project carousels",
                "ordering": ["position"],
            },
        ),
    ]
