# Generated by Django 3.1.2 on 2020-10-15 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Il titolo del progetto', max_length=50, null=True, verbose_name='Titolo')),
                ('intro', models.CharField(default='Un altro progetto di architettura.APP!', max_length=100, verbose_name='Introduzione')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
            },
        ),
    ]
