# Generated by Django 3.1.2 on 2021-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_squashed_0002_remove_project_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.CharField(choices=[('LP0', 'Altro'), ('LP1', 'Feasibility study'), ('LP2', 'Preliminary design'), ('LP3', 'Definitive design'), ('LP4', 'Authoring'), ('LP5', 'Construction design'), ('LP6', 'Tender design'), ('LP7', 'Project management'), ('LP8', 'Direzione lavori'), ('LP9', 'Maintenance design')], default='ALT', max_length=4, verbose_name='Performed activities'),
        ),
    ]
