# Generated by Django 3.1.2 on 2020-10-15 21:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-date',), 'verbose_name': 'Progetto', 'verbose_name_plural': 'Progetti'},
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_uploads', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Immagine',
                'verbose_name_plural': 'Immagini',
            },
        ),
    ]
