# Generated by Django 3.1.2 on 2020-12-21 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimblog', '0006_stationimage'),
        ('portfolio', '0001_squashed_0011_auto_20201222_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_project', to='bimblog.building', verbose_name='Building'),
        ),
    ]
