# Generated by Django 4.0.3 on 2022-04-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="body_en",
            new_name="body_de",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="intro_en",
            new_name="intro_de",
        ),
        migrations.RenameField(
            model_name="project",
            old_name="title_en",
            new_name="title_de",
        ),
        migrations.RenameField(
            model_name="projectcarousel",
            old_name="description_en",
            new_name="description_de",
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("ALT", "Altro"),
                    ("RES", "Residenziale"),
                    ("TER", "Uffici"),
                    ("SAN", "Ospedali"),
                    ("PRO", "Industrie"),
                    ("SCO", "Scuole"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Functional category",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost",
            field=models.CharField(
                choices=[
                    ("ALT", "Altro"),
                    ("1K", "1K"),
                    ("2K", "2K"),
                    ("5K", "5K"),
                    ("10K", "10K"),
                    ("20K", "20K"),
                    ("50K", "50K"),
                    ("100K", "100K"),
                    ("200K", "200K"),
                    ("500K", "500K"),
                    ("1M", "1M"),
                    ("2M", "2M"),
                    ("5M", "5M"),
                    ("10M", "10M"),
                    ("20M", "20M"),
                    ("50M", "50M"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Cost of intervention",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ALT", "Altro"),
                    ("PRO", "Progettato"),
                    ("COR", "In costruzione"),
                    ("REA", "Realizzato"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Status of intervention",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("ALT", "Altro"),
                    ("ARR", "Arredamento"),
                    ("RIS", "Ristrutturazione"),
                    ("RES", "Restauro"),
                    ("AMP", "Ampliamento"),
                    ("COS", "Costruzione"),
                    ("DEM", "Demolizione"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Type of intervention",
            ),
        ),
    ]
