# Generated by Django 3.1.2 on 2021-02-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='build',
        ),
    ]
