# Generated by Django 3.1.2 on 2020-10-31 22:30

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_squashed_0012_auto_20201023_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.CharField(default=portfolio.models.project_default_intro, max_length=100, verbose_name='Introduzione'),
        ),
        migrations.CreateModel(
            name='ProjectStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Il titolo della postazione fotografica', max_length=50, verbose_name='Titolo')),
                ('slug', models.SlugField(editable=False, max_length=100, null=True)),
                ('intro', models.CharField(default=portfolio.models.project_station_default_intro, max_length=100, verbose_name='Descrizione')),
                ('prog', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_station', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Stazione fotografica',
                'verbose_name_plural': 'Stazioni fotografiche',
                'ordering': ('prog', 'title'),
            },
        ),
    ]
