# Generated by Django 3.1.2 on 2020-10-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20201015_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('position',), 'verbose_name': 'Immagine', 'verbose_name_plural': 'Immagini'},
        ),
        migrations.AddField(
            model_name='projectimage',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.CharField(default='Un altro progetto di Grappelli Test!', max_length=100, verbose_name='Introduzione'),
        ),
    ]
