# Generated by Django 4.0.3 on 2022-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_body_en_project_body_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="full_de",
            field=models.CharField(max_length=32, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="activity",
            name="full_it",
            field=models.CharField(max_length=32, null=True, verbose_name="Name"),
        ),
    ]
