# Generated by Django 3.1.2 on 2021-09-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(max_length=32, verbose_name='Nome')),
                ('abbrev', models.CharField(max_length=4, verbose_name='Code name')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('abbrev',),
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='activity',
        ),
    ]
