# Generated by Django 3.1.2 on 2020-10-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201016_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.CharField(default='Un altro progetto di architettura.APP!', max_length=100, verbose_name='Introduzione'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='uploads/portfolio/projects/', verbose_name='Immagine'),
        ),
    ]
