# Generated by Django 3.1.2 on 2020-10-31 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201031_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstation',
            name='prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_station', to='portfolio.project', verbose_name='Progetto'),
        ),
        migrations.CreateModel(
            name='StationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data:')),
                ('image', models.ImageField(editable=False, max_length=200, null=True, upload_to='uploads/images/galleries/', verbose_name='Immagine')),
                ('fb_image', filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='Didascalia')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Posizione')),
                ('stat', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_image', to='portfolio.projectstation')),
            ],
            options={
                'verbose_name': 'Immagine',
                'verbose_name_plural': 'Immagini',
            },
        ),
    ]
