# Generated by Django 3.1.2 on 2021-09-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210908_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='activity',
            field=models.ManyToManyField(blank=True, to='portfolio.Activity', verbose_name='Performed activities'),
        ),
    ]
