# Generated by Django 4.0.3 on 2022-04-14 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_activity_full_de_activity_full_it"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="last_updated",
        ),
        migrations.AddField(
            model_name="project",
            name="client",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Client"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="date_end",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("ALT", "Other"),
                    ("RES", "Residential"),
                    ("TER", "Offices"),
                    ("SAN", "Hospitals"),
                    ("PRO", "Production"),
                    ("SCO", "Schools"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Functional category",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost",
            field=models.CharField(
                choices=[
                    ("ALT", "Other"),
                    ("1K", "1K"),
                    ("2K", "2K"),
                    ("5K", "5K"),
                    ("10K", "10K"),
                    ("20K", "20K"),
                    ("50K", "50K"),
                    ("100K", "100K"),
                    ("200K", "200K"),
                    ("500K", "500K"),
                    ("1M", "1M"),
                    ("2M", "2M"),
                    ("5M", "5M"),
                    ("10M", "10M"),
                    ("20M", "20M"),
                    ("50M", "50M"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Cost of intervention",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="site",
            field=models.CharField(
                blank=True,
                help_text="Loose location",
                max_length=100,
                null=True,
                verbose_name="Site",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("ALT", "Other"),
                    ("PRO", "Designed"),
                    ("COR", "Under construction"),
                    ("REA", "Done"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Status of intervention",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("ALT", "Other"),
                    ("ARR", "Furniture"),
                    ("RIS", "Refurbishment"),
                    ("RES", "Restoration"),
                    ("AMP", "Extension"),
                    ("COS", "Construction"),
                    ("DEM", "Demolition"),
                ],
                default="ALT",
                max_length=4,
                verbose_name="Type of intervention",
            ),
        ),
    ]
