# Generated by Django 3.1.2 on 2021-10-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='activity',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
