# Generated by Django 3.1.2 on 2020-11-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201031_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stationimage',
            options={'ordering': ('-date',), 'verbose_name': 'Immagine', 'verbose_name_plural': 'Immagini'},
        ),
        migrations.RemoveField(
            model_name='stationimage',
            name='position',
        ),
    ]
