# Generated by Django 3.1.2 on 2020-10-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201017_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(null=True, verbose_name='Testo'),
        ),
    ]
