# Generated by Django 3.1.2 on 2020-10-18 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_updated',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inserito il:'),
        ),
    ]
