# Generated by Django 3.1.2 on 2020-11-20 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filebrowser.fields
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20201103_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-date',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectstation',
            options={'ordering': ('prog', 'title'), 'verbose_name': 'Photo station', 'verbose_name_plural': 'Photo stations'},
        ),
        migrations.AlterModelOptions(
            name='stationimage',
            options={'ordering': ('-date',), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ALT', 'Altro'), ('RES', 'Residenziale'), ('TER', 'Terziario'), ('SAN', 'Sanitario'), ('PRO', 'Produttivo'), ('SCO', 'Scolastico')], default='ALT', max_length=4, verbose_name='Functional category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(choices=[('ALT', 'Altro'), ('1K', '1K'), ('10K', '10K'), ('100K', '100K'), ('1M', '1M'), ('10M', '10M')], default='ALT', max_length=4, verbose_name='Cost of intervention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.CharField(default=portfolio.models.project_default_intro, max_length=100, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.CharField(blank=True, help_text='Something like "Rome - Monteverde"', max_length=100, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ALT', 'Altro'), ('PRO', 'Progettato'), ('COR', 'In corso'), ('REA', 'Realizzato')], default='ALT', max_length=4, verbose_name='Status of intervention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the project', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('ALT', 'Altro'), ('ARR', 'Arredamento'), ('RIS', 'Ristrutturazione'), ('RES', 'Restauro'), ('AMP', 'Ampliamento'), ('COS', 'Costruzione'), ('DEM', 'Demolizione')], default='ALT', max_length=4, verbose_name='Type of intervention'),
        ),
        migrations.AlterField(
            model_name='projectstation',
            name='intro',
            field=models.CharField(default=portfolio.models.project_station_default_intro, max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectstation',
            name='prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_station', to='portfolio.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectstation',
            name='title',
            field=models.CharField(help_text='Title of the photo station', max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='image',
            field=models.ImageField(max_length=200, null=True, upload_to='uploads/images/galleries/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='stationimage',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_image', to='portfolio.projectstation', verbose_name='Station'),
        ),
    ]
