# Generated by Django 3.1.2 on 2020-11-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201120_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lat',
            field=models.FloatField(default=41.8988, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='project',
            name='long',
            field=models.FloatField(default=12.5451, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='project',
            name='zoom',
            field=models.FloatField(default=10, verbose_name='Zoom factor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ALT', 'Other'), ('RES', 'Residential'), ('TER', 'Offices'), ('SAN', 'Hospitals'), ('PRO', 'Production'), ('SCO', 'Schools')], default='ALT', max_length=4, verbose_name='Functional category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(choices=[('ALT', 'Other'), ('1K', '1K'), ('10K', '10K'), ('100K', '100K'), ('1M', '1M'), ('10M', '10M')], default='ALT', max_length=4, verbose_name='Cost of intervention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ALT', 'Other'), ('PRO', 'Designed'), ('COR', 'Under construction'), ('REA', 'Done')], default='ALT', max_length=4, verbose_name='Status of intervention'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('ALT', 'Other'), ('ARR', 'Furniture'), ('RIS', 'Refurbishment'), ('RES', 'Restoration'), ('AMP', 'Extension'), ('COS', 'Construction'), ('DEM', 'Demolition')], default='ALT', max_length=4, verbose_name='Type of intervention'),
        ),
    ]
