# Generated by Django 3.1.2 on 2020-10-20 15:00

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20201018_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='fb_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, null=True, verbose_name='Immagine'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(editable=False, max_length=200, null=True, upload_to='uploads/portfolio/projects/', verbose_name='Immagine'),
        ),
    ]
