# Generated by Django 3.1.2 on 2021-10-24 12:15

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20211024_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body_de',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='project',
            name='body_it',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_de',
            field=models.CharField(default=portfolio.models.project_default_intro, max_length=100, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='project',
            name='intro_it',
            field=models.CharField(default=portfolio.models.project_default_intro, max_length=100, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_de',
            field=models.CharField(blank=True, help_text='Title of the project', max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_it',
            field=models.CharField(blank=True, help_text='Title of the project', max_length=50, null=True, verbose_name='Title'),
        ),
    ]
