# Generated by Django 3.1.2 on 2020-11-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20201129_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstation',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='projectstation',
            name='long',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='project',
            name='zoom',
            field=models.FloatField(default=10, help_text='Collect these data fron https://openstreetmap.org', verbose_name='Zoom factor'),
        ),
    ]
