# Generated by Django 3.1.2 on 2020-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20201020_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('RES', 'Residenziale'), ('TER', 'Terziario'), ('SAN', 'Sanitario'), ('PRO', 'Produttivo'), ('ALT', 'Altro')], default='ALT', max_length=4, verbose_name='Categoria funzionale'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(choices=[('1K', '1K'), ('10K', '10K'), ('100K', '100K'), ('1M', '1M'), ('10M', '10M'), ('ALT', 'Altro')], default='ALT', max_length=4, verbose_name="Costo dell'intervento"),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('INP', 'In corso di progettazione'), ('PRO', 'Progettato'), ('INC', 'In corso di costruzione'), ('COS', 'Costruito'), ('IND', 'In corso di demolizione'), ('DEM', 'Demolito'), ('ALT', 'Altro')], default='ALT', max_length=4, verbose_name="Stato dell'intervento"),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('ARR', 'Arredamento'), ('RIS', 'Ristrutturazione'), ('RES', 'Restauro'), ('AMP', 'Ampliamento'), ('COS', 'Costruzione'), ('DEM', 'Demolizione'), ('ALT', 'Altro')], default='ALT', max_length=4, verbose_name='Tipo di intervento'),
        ),
    ]
