# Generated by Django 3.1.2 on 2020-12-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20201203_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstation',
            name='prog',
        ),
        migrations.RemoveField(
            model_name='stationimage',
            name='stat',
        ),
        migrations.RemoveField(
            model_name='project',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='project',
            name='long',
        ),
        migrations.RemoveField(
            model_name='project',
            name='map',
        ),
        migrations.RemoveField(
            model_name='project',
            name='zoom',
        ),
        migrations.DeleteModel(
            name='ProjectMapDxf',
        ),
        migrations.DeleteModel(
            name='ProjectStation',
        ),
        migrations.DeleteModel(
            name='StationImage',
        ),
    ]
