# Generated by Django 3.1.2 on 2020-10-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20201021_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ALT', 'Altro'), ('RES', 'Residenziale'), ('TER', 'Terziario'), ('SAN', 'Sanitario'), ('PRO', 'Produttivo'), ('SCO', 'Scolastico')], default='ALT', max_length=4, verbose_name='Categoria funzionale'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(choices=[('ALT', 'Altro'), ('1K', '1K'), ('10K', '10K'), ('100K', '100K'), ('1M', '1M'), ('10M', '10M')], default='ALT', max_length=4, verbose_name="Costo dell'intervento"),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ALT', 'Altro'), ('PRO', 'Progettato'), ('COR', 'In corso'), ('REA', 'Realizzato')], default='ALT', max_length=4, verbose_name="Stato dell'intervento"),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('ALT', 'Altro'), ('ARR', 'Arredamento'), ('RIS', 'Ristrutturazione'), ('RES', 'Restauro'), ('AMP', 'Ampliamento'), ('COS', 'Costruzione'), ('DEM', 'Demolizione')], default='ALT', max_length=4, verbose_name='Tipo di intervento'),
        ),
    ]
